/**:
  ros__parameters:
    joint_limits:
      shoulder_pan_joint:
        has_acceleration_limits: true
        max_acceleration: 5.0
        has_velocity_limits: true
        max_velocity: 3.15
        has_position_limits: true
        min_position: -6.28318530718
        max_position: 6.28318530718
      shoulder_lift_joint:
        has_acceleration_limits: true
        max_acceleration: 5.0
        has_velocity_limits: true
        max_velocity: 3.15
        has_position_limits: true
        min_position: -6.28318530718
        max_position: 6.28318530718
      elbow_joint:
        has_acceleration_limits: true
        max_acceleration: 5.0
        has_velocity_limits: true
        max_velocity: 3.15
        has_position_limits: true
        min_position: -6.28318530718
        max_position: 6.28318530718
      wrist_1_joint:
        has_acceleration_limits: true
        max_acceleration: 5.0
        has_velocity_limits: true
        max_velocity: 3.2
        has_position_limits: true
        min_position: -6.28318530718
        max_position: 6.28318530718
      wrist_2_joint:
        has_acceleration_limits: true
        max_acceleration: 5.0
        has_velocity_limits: true
        max_velocity: 3.2
        has_position_limits: true
        min_position: -6.28318530718
        max_position: 6.28318530718
      wrist_3_joint:
        has_acceleration_limits: true
        max_acceleration: 5.0
        has_velocity_limits: true
        max_velocity: 3.2
        has_position_limits: true
        min_position: -6.28318530718
        max_position: 6.28318530718
