/**:
  ros__parameters:
    controller_manager_ns: controller_manager
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
    moveit_simple_controller_manager:
      ros__parameters:
        controller_names:
          - joint_trajectory_controller

        joint_trajectory_controller:
          type: follow_joint_trajectory
          joints:
            - shoulder_pan_joint
            - shoulder_lift_joint
            - elbow_joint
            - wrist_1_joint
            - wrist_2_joint
            - wrist_3_joint
