/**:
  ros__parameters:
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters: >-
      default_planner_request_adapters/AddTimeOptimalParameterization
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints
    response_adapters: >-
      default_planner_response_adapters/AddTimeOptimalParameterization
      default_planner_response_adapters/ValidateSolution

    planner_configs:
      SBLkConfigDefault:
        type: geometric::SBL
        range: 0.0
      ESTkConfigDefault:
        type: geometric::EST
        range: 0.0
      LBKPIECEkConfigDefault:
        type: geometric::LBKPIECE
        range: 0.0
      BKPIECEkConfigDefault:
        type: geometric::BKPIECE
        range: 0.0
      KPIECEkConfigDefault:
        type: geometric::KPIECE
        range: 0.0
      RRTkConfigDefault:
        type: geometric::RRT
        range: 0.0
      RRTConnectkConfigDefault:
        type: geometric::RRTConnect
        range: 0.0
      RRTstarkConfigDefault:
        type: geometric::RRTstar
        range: 0.0
      TRRTkConfigDefault:
        type: geometric::TRRT
        range: 0.0
      PRMkConfigDefault:
        type: geometric::PRM
        range: 0.0
      PRMstarkConfigDefault:
        type: geometric::PRMstar
        range: 0.0
      FMTkConfigDefault:
        type: geometric::FMT
        range: 0.0
      BFMTkConfigDefault:
        type: geometric::BFMT
        range: 0.0
      PDSTkConfigDefault:
        type: geometric::PDST
        range: 0.0
      STRIDEkConfigDefault:
        type: geometric::STRIDE
        range: 0.0
      BiTRRTkConfigDefault:
        type: geometric::BiTRRT
        range: 0.0
      LBTRRTkConfigDefault:
        type: geometric::LBTRRT
        range: 0.0
      BiESTkConfigDefault:
        type: geometric::BiEST
        range: 0.0
      ProjESTkConfigDefault:
        type: geometric::ProjEST
        range: 0.0
      RRTXkConfigDefault:
        type: geometric::RRTXstatic
        range: 0.0
      InformedRRTstarkConfigDefault:
        type: geometric::InformedRRTstar
        range: 0.0
      AITkConfigDefault:
        type: geometric::AITstar
        range: 0.0

    ur_manipulator:
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        SBLkConfigDefault:
          type: geometric::SBL
          range: 0.0
        ESTkConfigDefault:
          type: geometric::EST
          range: 0.0
        LBKPIECEkConfigDefault:
          type: geometric::LBKPIECE
          range: 0.0
        BKPIECEkConfigDefault:
          type: geometric::BKPIECE
          range: 0.0
        KPIECEkConfigDefault:
          type: geometric::KPIECE
          range: 0.0
        RRTkConfigDefault:
          type: geometric::RRT
          range: 0.0
        RRTConnectkConfigDefault:
          type: geometric::RRTConnect
          range: 0.0
        RRTstarkConfigDefault:
          type: geometric::RRTstar
          range: 0.0
        TRRTkConfigDefault:
          type: geometric::TRRT
          range: 0.0
        PRMkConfigDefault:
          type: geometric::PRM
          range: 0.0
        PRMstarkConfigDefault:
          type: geometric::PRMstar
          range: 0.0
        FMTkConfigDefault:
          type: geometric::FMT
          range: 0.0
        BFMTkConfigDefault:
          type: geometric::BFMT
          range: 0.0
        PDSTkConfigDefault:
          type: geometric::PDST
          range: 0.0
        STRIDEkConfigDefault:
          type: geometric::STRIDE
          range: 0.0
        BiTRRTkConfigDefault:
          type: geometric::BiTRRT
          range: 0.0
        LBTRRTkConfigDefault:
          type: geometric::LBTRRT
          range: 0.0
        BiESTkConfigDefault:
          type: geometric::BiEST
          range: 0.0
        ProjESTkConfigDefault:
          type: geometric::ProjEST
          range: 0.0
        RRTXkConfigDefault:
          type: geometric::RRTXstatic
          range: 0.0
        InformedRRTstarkConfigDefault:
          type: geometric::InformedRRTstar
          range: 0.0
        AITkConfigDefault:
          type: geometric::AITstar
          range: 0.0
